version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  commands:
    - python -m pip install pdm
    - python -m pdm install --dev --no-self
    - python -m mkdocs build -d _readthedocs/html
