site_name: pyndow
site_url: https://github.com/orgoms/pyndow
site_author: Zenthm
site_description: A modern Python library for OpenGL context/window management
copyright: Copyright &copy 2024-present Zenthm <zenthm.dev@gmail.com>
repo_url: https://github.com/orgoms/pyndow
repo_name: GitHub
edit_uri_template: blob/main/CONTRIBUTING.md

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
