site_name: pyndow
site_url: https://github.com/orgoms/pyndow
site_author: Zenthm
site_description: A modern Python library for OpenGL context/window management
copyright: Copyright &copy 2024-present Zenthm <zenthm.dev@gmail.com>
repo_url: https://github.com/orgoms/pyndow
repo_name: GitHub
edit_uri_template: blob/main/CONTRIBUTING.md

theme:
  name: material
